### ISSUE TITLE
Bug: Tado stopped working, change in auth

### ISSUE THREAD

**Issue by lubbertkramer** [lubbertkramer/home_assistant_config#161]
https://github.com/home-assistant/home-assistant/pull/22145 

Update will be in 0.90, manual fix by -> https://gathering.tweakers.net/forum/list_message/58281550#58281550

**Comment by mlipovsky** [comment]
Still not working on 0.90:

Thu Mar 21 2019 04:47:36 GMT+0100 (Central European Standard Time)
Error 401 on https://auth.tado.com/api/v2/me?username={username}&password={password}.

**Comment by wmalgadey** [comment]
https://github.com/home-assistant/home-assistant/pull/22242 should fix this issue too
